In [1]:
import numpy as np 
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [2]:
arr[6]

np.int64(17)

In [3]:
arr[1:5]

array([12, 13, 14, 15])

In [4]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

In [10]:
#numpy indexing and slicing of a matrix
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [12]:
arr[0,0]

np.int64(1)

In [13]:
arr[0,4]

np.int64(5)

In [14]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [15]:
slice1=arr[3:,3:]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
#boolean indexing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [18]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])