In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
np.array(arr)

array([1, 2, 3, 4])

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#array genration functions 
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [14]:
#random number genration
np.random.rand(10)

array([0.88900059, 0.87892273, 0.02582854, 0.09397774, 0.40808193,
       0.36379869, 0.23992945, 0.93172806, 0.9272863 , 0.15074862])

In [15]:
np.random.randn(10)

array([ 0.02696163,  1.89534627, -2.46343895,  0.60894608, -0.82250872,
       -0.01057804,  0.80523185, -0.79199356, -0.52829143, -0.37395636])

In [16]:
np.random.randint(6)

4

In [17]:
np.random.randint(10,20,10)

array([18, 17, 19, 12, 13, 18, 12, 16, 13, 19], dtype=int32)

In [18]:
#attributes
arr = np.array([[1,2,3],[4,6,7]])
arr

array([[1, 2, 3],
       [4, 6, 7]])

In [19]:
arr.shape

(2, 3)

In [20]:
arr.size

6

In [21]:
arr.dtype

dtype('int64')

In [23]:
#array methods
arr.min()



np.int64(1)

In [24]:
arr.max()

np.int64(7)

In [25]:
arr.sum()

np.int64(23)

In [26]:
np.sum(arr,axis=0)

array([ 5,  8, 10])

In [27]:
arr.mean()

np.float64(3.8333333333333335)

In [28]:
arr.std()

np.float64(2.1147629234082532)

In [29]:
arr.argmax()

np.int64(5)

In [30]:
arr.argmin()

np.int64(0)